services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: symfony_php
        working_dir: /var/www
        volumes:
            - .:/var/www/
        networks:
            - symfony_net

    nginx:
        image: nginx:stable-alpine
        container_name: symfony_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - symfony_net

    db:
        image: mysql:8.4
        container_name: symfony_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - symfony_net

    redis:
        image: redis:7-alpine
        container_name: symfony_redis
        ports:
            - "6379:6379"
        networks:
            - symfony_net

volumes:
    db_data:

networks:
    symfony_net:
        driver: bridge
